### ISSUE TITLE
Estimate for when the code will be available?

### ISSUE THREAD

**Issue by Flux9665** [xinjli/transphone#1]
Hi! I saw your excellent work at ACL, read the paper and talked to David at the poster. I'm very excited to try it out for in combination with the crosslingual text-to-speech I'm working on. Do you have an estimate when the code (and hopfully models) will be available?

**Comment by xinjli** [comment]
Hi thanks for your comment!
I am mostly done cleaning up my code but I am a bit busy doing my internship recently
I hope I can release code sometime this month :)

**Comment by xinjli** [comment]
hi, it becomes available. sorry for the late release
