### ISSUE TITLE
UnicodeDecodeError and NotADirectoryError

### ISSUE THREAD

**Issue by Flux9665** [xinjli/transphone#5]
Hi Xinjian! Thank you for building this awesome package! I've been using transphone on linux so far and it's working well, however today I tried running it on a Windows machine and ran into an issue. 

When I run ```model = read_g2p()```, I get the following error:

```
File "venv\lib\site-packages\transphone\g2p.py", line 38, in __init__
    self.grapheme_vocab = Vocab.read(model_path / 'grapheme.vocab')
File "\venv\lib\site-packages\transphone\data\vocab.py", line 22, in read
    for i, line in enumerate(open(Path(file_path))):
File "C:\Users\Flux\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 5437: character maps to <undefined>
```

It can be fixed by adding ```encoding="utf8"``` here:

https://github.com/xinjli/transphone/blob/f3bb4160b23149aeddc13463fe942deea9c65410/transphone/data/vocab.py#L22

However after that I found another issue: I got a ```NotADirectoryError``` when the tarfile is being unpacked in the following line:

https://github.com/xinjli/transphone/blob/f3bb4160b23149aeddc13463fe942deea9c65410/transphone/bin/download_model.py#L30

This one I couldn't figure out yet. It says that ```...\\model\\latest\\prn``` is an invalid name for a directoy. I suspect the double backslashes to be the problem (which would explain why it's a windows exclusive problem). I just don't see why there are double backslashes. Do you have any hints on that?

**Comment by xinjli** [comment]
hi, thanks for your issue.

It seems that windows does not allow a few specific directory name including prn as it coincides with some system specific names. I uses the same name for the corresponding language id in a dependency repository I am managing https://github.com/xinjli/phonepiece 

I updated it to fix this problem and can you try updating its version to 1.0.9. Can you try updating phonepiece version in your windows and retry it. No update is needed for transphone.

Thanks

**Comment by Flux9665** [comment]
Thanks for the quick help! I did a clean reinstall of transphone and upgraded phonepiece. However version 1.0.9 was not available via pip. I previously had version 1.0.7 and have now upgraded to version 1.0.8 instead.

I still had the problem with the encoding in transphone itself in the following line:

https://github.com/xinjli/transphone/blob/f3bb4160b23149aeddc13463fe942deea9c65410/transphone/data/vocab.py#L22

After fixing this locally again, instanciating the model worked! However I now get a different error during inference:

```
model.inference('transphone', 'eng')

File "...\transphone\g2p.py", line 134, in inference
    inv = read_inventory(lang_id)
File "...\phonepiece\inventory.py", line 35, in read_inventory
    raise ValueError(f"could not download or read {model_name} inventory")
ValueError: could not download or read latest inventory
```

I cleared out the cache manually (```(model_dir / model_name).rmdir()``` unfortunately doesn't work under windows, it can only delete empty dirs. You could use ```shutil.rmtree('/folder_name', ignore_errors=True)``` instead). Then I tried downloading again and got the same error as the last time, however with a different path: ```...\\model\\latest\\aux``` I assume the case with _aux_ is the same as for _prn_.

**Comment by xinjli** [comment]
interesting, yeah, it seems 4 names with 3 chars are not allowed
https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file

I uploaded it again to version 1.0.9 this time, can you try again?

**Comment by Flux9665** [comment]
Works now, awesome, thank you very much!
